# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvUksimTSE3Bii30A_-l1CxlJN7mOJdq
"""

import pandas as pd
guruh=pd.DataFrame({
    'Ism ':[   'Muhammaddiyor ','Asror','Imomali','Dilshod' ,'Sarvar','Oybek','Jorabek','Alisher','Ilhom','Humoyun'  ],
    'Familya ':[ 'Tolibjonov','Alimqulov','Nuridinjonov','Ikromaliyiv','Shakirjonov','Turonboyov', 'Tursinaliyev','Erkinov','Abdulhakimov','Hasanboyev'   ],
    'Manzili':[ 'Bogdod','Namangan','Quvasoy','Toshkent','Bogdod','Beshariq','Bogdod','Beshariq','Vadil','Andijon'    ],
    'Telfon raqam':['910080402','947700585','770200103','908291301','123456789','987654321','908598075','445454444','774874748','4745641465641']


})
print(guruh)

guruh.to_excel('guruh.xlsx')